"""
Generator สำหรับ sandbox/rules/rule_table.json — 27-row lookup table ที่ map
(Model A class, Model B class, Model C class) -> final signal (BUY/HOLD/SELL)

เขียนเป็น generator แทนการพิมพ์ 27 แถวด้วยมือ เพื่อให้ formula ที่ใช้สร้างตาราง (weight +
threshold) เห็นชัดเจน ตรวจสอบซ้ำได้ และแก้ทีเดียวได้ทั้งตารางถ้าจะเปลี่ยน weight/threshold
— ตัวตารางเองที่ engine.py ใช้จริงคือไฟล์ JSON ที่ generate ออกมา (แก้ตรง ๆ ในไฟล์ JSON
ก็ได้ถ้าอยากปรับเป็นรายแถว ไม่จำเป็นต้องรัน generator ใหม่)

Default rule design (ตัดสินใจเป็นค่าเริ่มต้นสำหรับ sandbox — ยังไม่ผ่าน validation ใดๆ
ต้อง revisit ตอนมีโมเดลจริง):
  - แปลง class เป็น weight ทิศทาง: buy/positive = +1, hold/neutral = 0, sell/negative = -1
  - weighted score = 0.5*A + 0.3*B + 0.2*C
    (ให้ Model A น้ำหนักมากสุดเพราะเป็น fundamental ระยะยาว, B รองลงมาเพราะเป็นข่าวเฉพาะตัว,
    C น้อยสุดเพราะเป็นสัญญาณ macro/sector กว้าง ๆ และผล exp_01/exp_02 ที่ผ่านมายังอ่อน —
    ดู experiments/log.md)
  - threshold: score >= 0.3 -> BUY, score <= -0.3 -> SELL, อื่น ๆ -> HOLD
    (ได้ผลลัพธ์สมดุลพอดี 9 BUY / 9 HOLD / 9 SELL จาก 27 combo)

รัน: python3 sandbox/scripts/generate_rule_table.py
"""

import json
from pathlib import Path

OUT_PATH = Path(__file__).resolve().parent.parent / "rules" / "rule_table.json"

A_CLASSES = [("buy", 1), ("hold", 0), ("sell", -1)]
BC_CLASSES = [("positive", 1), ("neutral", 0), ("negative", -1)]

WEIGHT_A, WEIGHT_B, WEIGHT_C = 0.5, 0.3, 0.2
BUY_THRESHOLD, SELL_THRESHOLD = 0.3, -0.3


def build_rows():
    rows = []
    for a_cls, a_w in A_CLASSES:
        for b_cls, b_w in BC_CLASSES:
            for c_cls, c_w in BC_CLASSES:
                score = round(WEIGHT_A * a_w + WEIGHT_B * b_w + WEIGHT_C * c_w, 4)
                if score >= BUY_THRESHOLD:
                    signal = "BUY"
                elif score <= SELL_THRESHOLD:
                    signal = "SELL"
                else:
                    signal = "HOLD"
                rows.append(
                    {
                        "model_a_class": a_cls,
                        "model_b_class": b_cls,
                        "model_c_class": c_cls,
                        "weighted_score": score,
                        "signal": signal,
                    }
                )
    return rows


def main():
    rows = build_rows()
    assert len(rows) == 27, f"expected 27 rows, got {len(rows)}"

    from collections import Counter

    counts = Counter(r["signal"] for r in rows)
    print(f"Generated {len(rows)} rows: {dict(counts)}")

    payload = {
        "meta": {
            "description": "Default rule engine lookup table (Model A x B x C -> signal). "
            "Generated by sandbox/scripts/generate_rule_table.py — edit that script and "
            "regenerate, or edit this file directly for one-off row tweaks.",
            "weights": {"model_a": WEIGHT_A, "model_b": WEIGHT_B, "model_c": WEIGHT_C},
            "thresholds": {"buy": BUY_THRESHOLD, "sell": SELL_THRESHOLD},
            "signal_counts": dict(counts),
        },
        "rows": rows,
    }
    OUT_PATH.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
